# Generated by Django 5.2.8 on 2025-11-06 02:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('data_nascimento', models.DateField()),
                ('responsavel', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('amarelo', 'Amarelo'), ('vermelho', 'Vermelho'), ('clinico', 'Clínico')], max_length=20)),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pendente', max_length=20)),
                ('bebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='medicacoes.bebe')),
            ],
        ),
        migrations.CreateModel(
            name='Medicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('dosagem', models.CharField(help_text='Ex: 5 ml, 1 comprimido', max_length=80)),
                ('frequencia', models.CharField(choices=[('diaria', 'Diária'), ('2x_dia', '2x por dia'), ('3x_dia', '3x por dia'), ('semanal', 'Semanal'), ('mensal', 'Mensal')], max_length=20)),
                ('via', models.CharField(default='oral', max_length=50)),
                ('duracao_dias', models.IntegerField(blank=True, help_text='Duração prevista em dias', null=True)),
                ('data_inicio', models.DateField(default=django.utils.timezone.now)),
                ('cuidados', models.TextField(blank=True)),
                ('bebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicacoes', to='medicacoes.bebe')),
            ],
        ),
        migrations.CreateModel(
            name='Lembrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField()),
                ('canal', models.CharField(default='app', help_text='app, sms, whatsapp', max_length=20)),
                ('medicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lembretes', to='medicacoes.medicacao')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_total', models.DecimalField(decimal_places=2, help_text='Quantidade total em unidade definida (ex: ml ou comprimidos)', max_digits=10)),
                ('unidade', models.CharField(default='ml', max_length=30)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('medicacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estoque', to='medicacoes.medicacao')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAdministracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('horario', models.TimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('dei', 'Dei'), ('esqueci', 'Esqueci'), ('vomitou', 'Vomitou'), ('recusou', 'Recusou')], max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('medicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='medicacoes.medicacao')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
